name: contactos
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  path: ^1.9.0
  path_provider: ^2.1.5
  image_picker: ^1.0.7
  drift: ^2.30.0
  drift_flutter: ^0.2.8
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  drift_dev: ^2.30.0
  build_runner: ^2.10.4
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
